ALTER TABLE sessions ADD COLUMN IF NOT EXISTS host_id TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT false;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS max_participants INTEGER DEFAULT 10;

ALTER TABLE participants ADD COLUMN IF NOT EXISTS is_host BOOLEAN DEFAULT false;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS joined_at TIMESTAMP DEFAULT NOW();
ALTER TABLE participants ADD COLUMN IF NOT EXISTS last_active TIMESTAMP DEFAULT NOW();
ALTER TABLE participants ADD COLUMN IF NOT EXISTS avatar TEXT;
